# Uncomment the next line to define a global platform for your project
platform :ios ,'9.0'
inhibit_all_warnings!

target 'PT-SegmentedControlDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Masonry'

  # Pods for PT-SegmentedControlDemo

end
